services:
  langample:
    build:
      context: ./langample
      args:
        - BIN_FILE=${HOST_PATH_BIN:?path to the executable must be set}
        - API_KEY_CHATGPT=${API_KEY_CHATGPT:?ChatGPT API key must be set}
    restart: unless-stopped
    ports:
      - "8080:8080"
