name: deploy

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-release
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.88.0"
          override: true
          profile: minimal

      - name: Build backend (release)
        run: |
          cd backend
          cargo build --package backend --bin backend --release
          cd ..
          # Ensure it exists
          test -f ./backend/target/release/backend

      - name: Upload backend binary
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ./backend/target/release/backend
          target: /tmp/

      - name: Upload deploy script
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ./cicd/deploy.py
          target: /tmp/

      - name: Remote deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -euo pipefail
            python3 /tmp/cicd/deploy.py \
              --binary-path /tmp/backend/target/release/backend \
              --repo-url https://github.com/${{ github.repository }} \
              --api-key-chatgpt ${{ secrets.API_KEY_CHATGPT }} \
              --graphql-parent-path /langample/ \
              --panlex-sqlite-db-path ~/panlex.sqlite
