name: deploy

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-release
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build fat JAR
        run: cd backend && ./gradlew buildFatJar

      - name: Upload fat JAR
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ./backend/build/libs/langample-all.jar
          target: /tmp/

      - name: Upload deploy script
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ./cicd/deploy.py
          target: /tmp/

      - name: Remote deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -euo pipefail
            python3 /tmp/cicd/deploy.py \
              --jar-path /tmp/backend/build/libs/langample-all.jar \
              --repo-url https://github.com/${{ github.repository }} \
              --api-key-chatgpt ${{ secrets.API_KEY_CHATGPT }}